package com.zhuanche.entity.rentcar;

import java.io.Serializable;

public class District implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.del_flag
     *
     * @mbggenerated
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.creator_id
     *
     * @mbggenerated
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.del_id
     *
     * @mbggenerated
     */
    private Integer delId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.del_name
     *
     * @mbggenerated
     */
    private String delName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.del_time
     *
     * @mbggenerated
     */
    private Integer delTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.start_date
     *
     * @mbggenerated
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.end_date
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.point
     *
     * @mbggenerated
     */
    private String point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car_biz_district.baidu_point
     *
     * @mbggenerated
     */
    private String baiduPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car_biz_district
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.id
     *
     * @return the value of car_biz_district.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.id
     *
     * @param id the value for car_biz_district.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.name
     *
     * @return the value of car_biz_district.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.name
     *
     * @param name the value for car_biz_district.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.description
     *
     * @return the value of car_biz_district.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.description
     *
     * @param description the value for car_biz_district.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.city_name
     *
     * @return the value of car_biz_district.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.city_name
     *
     * @param cityName the value for car_biz_district.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.city_id
     *
     * @return the value of car_biz_district.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.city_id
     *
     * @param cityId the value for car_biz_district.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.del_flag
     *
     * @return the value of car_biz_district.del_flag
     *
     * @mbggenerated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.del_flag
     *
     * @param delFlag the value for car_biz_district.del_flag
     *
     * @mbggenerated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.status
     *
     * @return the value of car_biz_district.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.status
     *
     * @param status the value for car_biz_district.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.remark
     *
     * @return the value of car_biz_district.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.remark
     *
     * @param remark the value for car_biz_district.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.creator_id
     *
     * @return the value of car_biz_district.creator_id
     *
     * @mbggenerated
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.creator_id
     *
     * @param creatorId the value for car_biz_district.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.creator_name
     *
     * @return the value of car_biz_district.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.creator_name
     *
     * @param creatorName the value for car_biz_district.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.create_time
     *
     * @return the value of car_biz_district.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.create_time
     *
     * @param createTime the value for car_biz_district.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.del_id
     *
     * @return the value of car_biz_district.del_id
     *
     * @mbggenerated
     */
    public Integer getDelId() {
        return delId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.del_id
     *
     * @param delId the value for car_biz_district.del_id
     *
     * @mbggenerated
     */
    public void setDelId(Integer delId) {
        this.delId = delId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.del_name
     *
     * @return the value of car_biz_district.del_name
     *
     * @mbggenerated
     */
    public String getDelName() {
        return delName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.del_name
     *
     * @param delName the value for car_biz_district.del_name
     *
     * @mbggenerated
     */
    public void setDelName(String delName) {
        this.delName = delName == null ? null : delName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.del_time
     *
     * @return the value of car_biz_district.del_time
     *
     * @mbggenerated
     */
    public Integer getDelTime() {
        return delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.del_time
     *
     * @param delTime the value for car_biz_district.del_time
     *
     * @mbggenerated
     */
    public void setDelTime(Integer delTime) {
        this.delTime = delTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.type
     *
     * @return the value of car_biz_district.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.type
     *
     * @param type the value for car_biz_district.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.start_date
     *
     * @return the value of car_biz_district.start_date
     *
     * @mbggenerated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.start_date
     *
     * @param startDate the value for car_biz_district.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.end_date
     *
     * @return the value of car_biz_district.end_date
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.end_date
     *
     * @param endDate the value for car_biz_district.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.point
     *
     * @return the value of car_biz_district.point
     *
     * @mbggenerated
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.point
     *
     * @param point the value for car_biz_district.point
     *
     * @mbggenerated
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car_biz_district.baidu_point
     *
     * @return the value of car_biz_district.baidu_point
     *
     * @mbggenerated
     */
    public String getBaiduPoint() {
        return baiduPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car_biz_district.baidu_point
     *
     * @param baiduPoint the value for car_biz_district.baidu_point
     *
     * @mbggenerated
     */
    public void setBaiduPoint(String baiduPoint) {
        this.baiduPoint = baiduPoint == null ? null : baiduPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_biz_district
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        District other = (District) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreatorId() == null ? other.getCreatorId() == null : this.getCreatorId().equals(other.getCreatorId()))
            && (this.getCreatorName() == null ? other.getCreatorName() == null : this.getCreatorName().equals(other.getCreatorName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDelId() == null ? other.getDelId() == null : this.getDelId().equals(other.getDelId()))
            && (this.getDelName() == null ? other.getDelName() == null : this.getDelName().equals(other.getDelName()))
            && (this.getDelTime() == null ? other.getDelTime() == null : this.getDelTime().equals(other.getDelTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_biz_district
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreatorId() == null) ? 0 : getCreatorId().hashCode());
        result = prime * result + ((getCreatorName() == null) ? 0 : getCreatorName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDelId() == null) ? 0 : getDelId().hashCode());
        result = prime * result + ((getDelName() == null) ? 0 : getDelName().hashCode());
        result = prime * result + ((getDelTime() == null) ? 0 : getDelTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_biz_district
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", cityName=").append(cityName);
        sb.append(", cityId=").append(cityId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", creatorName=").append(creatorName);
        sb.append(", createTime=").append(createTime);
        sb.append(", delId=").append(delId);
        sb.append(", delName=").append(delName);
        sb.append(", delTime=").append(delTime);
        sb.append(", type=").append(type);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}