package com.zhuanche.service.driver;

import com.zhuanche.entity.driver.DriverCityWhite;

import java.util.List;

public interface DriverCityWhiteService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    DriverCityWhite selectByPrimaryKey(Integer id);

    /**
     * 查询所有有效的白名单城市
     * @return
     */
    List<DriverCityWhite> findList();

}
