package com.zhuanche.dao;

import com.zhuanche.entity.RolePermission;

import java.util.List;

public interface RolePermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_permission
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    Integer deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_permission
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    Integer insert(RolePermission rolePermission);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_permission
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    Integer insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_permission
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm_role_permission
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    Integer updateByPrimaryKeySelective(RolePermission record);

    Integer insertByBatch(List<RolePermission> rolePermissions);

    Integer deleteByRoleId(Long rid);
}