package com.zhuanche.dao.driver;

import com.zhuanche.entity.driver.DriverCityWhite;

import java.util.List;

public interface DriverCityWhiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    int insert(DriverCityWhite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    int insertSelective(DriverCityWhite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    DriverCityWhite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DriverCityWhite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DriverCityWhite record);

    List<DriverCityWhite> findList() ;
}