package com.zhuanche.entity.driver;

import java.io.Serializable;
import java.util.Date;

public class DriverCityWhite implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.validate_status
     *
     * @mbggenerated
     */
    private Byte validateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.validate_date
     *
     * @mbggenerated
     */
    private Date validateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_city_white_list.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.id
     *
     * @return the value of driver_city_white_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.id
     *
     * @param id the value for driver_city_white_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.city_name
     *
     * @return the value of driver_city_white_list.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.city_name
     *
     * @param cityName the value for driver_city_white_list.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.city_id
     *
     * @return the value of driver_city_white_list.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.city_id
     *
     * @param cityId the value for driver_city_white_list.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.status
     *
     * @return the value of driver_city_white_list.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.status
     *
     * @param status the value for driver_city_white_list.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.validate_status
     *
     * @return the value of driver_city_white_list.validate_status
     *
     * @mbggenerated
     */
    public Byte getValidateStatus() {
        return validateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.validate_status
     *
     * @param validateStatus the value for driver_city_white_list.validate_status
     *
     * @mbggenerated
     */
    public void setValidateStatus(Byte validateStatus) {
        this.validateStatus = validateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.validate_date
     *
     * @return the value of driver_city_white_list.validate_date
     *
     * @mbggenerated
     */
    public Date getValidateDate() {
        return validateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.validate_date
     *
     * @param validateDate the value for driver_city_white_list.validate_date
     *
     * @mbggenerated
     */
    public void setValidateDate(Date validateDate) {
        this.validateDate = validateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.create_time
     *
     * @return the value of driver_city_white_list.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.create_time
     *
     * @param createTime the value for driver_city_white_list.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_city_white_list.update_time
     *
     * @return the value of driver_city_white_list.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_city_white_list.update_time
     *
     * @param updateTime the value for driver_city_white_list.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DriverCityWhite other = (DriverCityWhite) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getValidateStatus() == null ? other.getValidateStatus() == null : this.getValidateStatus().equals(other.getValidateStatus()))
            && (this.getValidateDate() == null ? other.getValidateDate() == null : this.getValidateDate().equals(other.getValidateDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getValidateStatus() == null) ? 0 : getValidateStatus().hashCode());
        result = prime * result + ((getValidateDate() == null) ? 0 : getValidateDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver_city_white_list
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cityName=").append(cityName);
        sb.append(", cityId=").append(cityId);
        sb.append(", status=").append(status);
        sb.append(", validateStatus=").append(validateStatus);
        sb.append(", validateDate=").append(validateDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}