package com.zhuanche.entity;

public class AdminRole {

    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_admin_role.UID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_admin_role.RID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.ID
     *
     * @return the value of crm_admin_role.ID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.ID
     *
     * @param id the value for crm_admin_role.ID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.UID
     *
     * @return the value of crm_admin_role.UID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.UID
     *
     * @param uid the value for crm_admin_role.UID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_admin_role.RID
     *
     * @return the value of crm_admin_role.RID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_admin_role.RID
     *
     * @param rid the value for crm_admin_role.RID
     *
     * @mbggenerated Tue Aug 15 10:00:28 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}