package com.zhuanche.entity;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_permission.id
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_permission.rid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_role_permission.pid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    private Long pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_permission.id
     *
     * @return the value of crm_role_permission.id
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_permission.id
     *
     * @param id the value for crm_role_permission.id
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_permission.rid
     *
     * @return the value of crm_role_permission.rid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_permission.rid
     *
     * @param rid the value for crm_role_permission.rid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_role_permission.pid
     *
     * @return the value of crm_role_permission.pid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_role_permission.pid
     *
     * @param pid the value for crm_role_permission.pid
     *
     * @mbggenerated Mon Aug 14 11:52:21 CST 2017
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}